import os
import csv
from datetime import datetime
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from io import BytesIO
import json

def generate_response_pdf(event_id, form_id, event_data=None, form_data=None):
    """
    Generate PDF for form responses
    """
    csv_path = f'data/events/{event_id}/{form_id}.csv'
    
    if not os.path.exists(csv_path):
        return None
    
    # Read CSV data
    data = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            data.append(row)
    
    if len(data) <= 1:  # Only header or no data
        return None
    
    # Create PDF in memory
    buffer = BytesIO()
    
    # Use landscape for better table display
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    # Title Style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        alignment=1,
        spaceAfter=12,
        textColor=colors.HexColor('#4a6baf')
    )
    
    # Subtitle Style
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading3'],
        fontSize=12,
        alignment=1,
        spaceAfter=20,
        textColor=colors.grey
    )
    
    # Add Title
    if event_data and form_data:
        title_text = f"{event_data.get('name', 'Event')} - {form_data.get('title', 'Form')}"
        elements.append(Paragraph(title_text, title_style))
        
        # Add subtitle with date
        date_text = f"Responses Report - Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        elements.append(Paragraph(date_text, subtitle_style))
    else:
        elements.append(Paragraph("Form Responses Report", title_style))
    
    # Summary information
    summary_style = ParagraphStyle(
        'SummaryStyle',
        parent=styles['Normal'],
        fontSize=10,
        alignment=0,
        spaceAfter=15
    )
    
    total_responses = len(data) - 1
    summary_text = f"Total Responses: {total_responses}"
    elements.append(Paragraph(summary_text, summary_style))
    
    # Create table from CSV data
    # We'll limit the number of columns shown to avoid overwhelming the PDF
    max_columns = 8  # Maximum columns to display
    
    if len(data[0]) > max_columns:
        # If too many columns, show first few and last few
        header_row = data[0]
        table_data = [header_row[:max_columns-1] + ['...'] + header_row[-1:]]
        
        for row in data[1:]:
            table_row = row[:max_columns-1] + ['...'] + row[-1:]
            table_data.append(table_row)
    else:
        table_data = data
    
    # Create table
    table = Table(table_data)
    
    # Style the table
    table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4a6baf')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ])
    
    # Add alternate row colors
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            bg_color = colors.whitesmoke
        else:
            bg_color = colors.white
        table_style.add('BACKGROUND', (0, i), (-1, i), bg_color)
    
    table.setStyle(table_style)
    
    # Set column widths
    if table_data:
        col_count = len(table_data[0])
        col_width = doc.width / col_count
        table._argW = [col_width] * col_count
    
    elements.append(table)
    
    # Add footer information
    elements.append(Spacer(1, 20))
    
    footer_style = ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=8,
        alignment=1,
        textColor=colors.grey,
        spaceBefore=20
    )
    
    if len(data[0]) > max_columns:
        footer_text = f"Note: Showing {max_columns} columns out of {len(data[0])} total columns for better readability."
        elements.append(Paragraph(footer_text, footer_style))
    
    elements.append(Paragraph("Generated by Event Registration System", footer_style))
    
    # Build PDF
    doc.build(elements)
    
    buffer.seek(0)
    return buffer.getvalue()

def generate_detailed_pdf(event_id, form_id):
    """
    Generate a more detailed PDF with individual response breakdown
    """
    csv_path = f'data/events/{event_id}/{form_id}.csv'
    
    if not os.path.exists(csv_path):
        return None
    
    # Read CSV data
    data = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            data.append(row)
    
    if len(data) <= 1:
        return None
    
    # Load event and form data
    event_data = None
    form_data = None
    
    event_json_path = f'data/events/{event_id}.json'
    if os.path.exists(event_json_path):
        with open(event_json_path, 'r') as f:
            event_data = json.load(f)
            for form in event_data.get('forms', []):
                if form['id'] == form_id:
                    form_data = form
                    break
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=16,
        alignment=1,
        spaceAfter=6,
        textColor=colors.HexColor('#4a6baf')
    )
    
    if event_data and form_data:
        title = f"Detailed Report: {form_data.get('title', 'Form')}"
        elements.append(Paragraph(title, title_style))
        elements.append(Paragraph(f"Event: {event_data.get('name', 'Event')}", styles['Heading3']))
    
    # Summary
    elements.append(Spacer(1, 10))
    summary_text = f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>"
    summary_text += f"Total responses: {len(data) - 1}<br/>"
    summary_text += f"Total questions: {len(data[0]) - 2}"  # Subtract timestamp and response_id
    
    summary_para = Paragraph(summary_text, styles['Normal'])
    elements.append(summary_para)
    elements.append(Spacer(1, 20))
    
    # Response breakdown (show first 5 responses in detail)
    header = data[0]
    max_responses_to_show = min(5, len(data) - 1)
    
    if max_responses_to_show > 0:
        elements.append(Paragraph(f"Showing first {max_responses_to_show} responses:", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        for i in range(1, max_responses_to_show + 1):
            response = data[i]
            elements.append(Paragraph(f"<b>Response #{i}</b>", styles['Heading4']))
            
            # Create a table for this response
            response_data = []
            for j in range(2, min(len(header), 10)):  # Show first 8 questions
                if j < len(response):
                    response_data.append([header[j], response[j]])
            
            if response_data:
                response_table = Table(response_data, colWidths=[2*inch, 3*inch])
                response_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                ]))
                elements.append(response_table)
            
            elements.append(Spacer(1, 15))
    
    # Add summary table
    elements.append(Paragraph("Summary Statistics", styles['Heading3']))
    elements.append(Spacer(1, 10))
    
    summary_table_data = [
        ['Metric', 'Value'],
        ['Total Responses', str(len(data) - 1)],
        ['Questions in Form', str(len(data[0]) - 2)],
        ['First Response', data[1][0] if len(data) > 1 else 'N/A'],
        ['Latest Response', data[-1][0] if len(data) > 1 else 'N/A'],
    ]
    
    summary_table = Table(summary_table_data, colWidths=[2*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4a6baf')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ]))
    
    elements.append(summary_table)
    
    # Footer
    elements.append(Spacer(1, 20))
    footer = Paragraph(
        "Generated by Event Registration System - https://youreventdomain.com",
        styles['Italic']
    )
    elements.append(footer)
    
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
